// general
export const LISTFROMTEXT_RAPIDAPI_HOST = 'listfromtext.p.rapidapi.com'
export const LISTFROMTEXT_RAPIDAPI_BASE_URL = `https://${LISTFROMTEXT_RAPIDAPI_HOST}`

const FILE = '/file'
const EXTRACTOR = '/extractor'

export const FILE_TEXT = `${FILE}/text`
export const FILE_EXTRACTOR_ALPHANUMERIC = `${FILE}${EXTRACTOR}/alphanumeric`
export const FILE_EXTRACTOR_BITCOIN_WALLET = `${FILE}${EXTRACTOR}/bitcoin-wallet`
export const FILE_EXTRACTOR_CREDIT_CARD = `${FILE}${EXTRACTOR}/credit-card`
export const FILE_EXTRACTOR_CUSTOM_REGEX = `${FILE}${EXTRACTOR}/custom-regex`
export const FILE_EXTRACTOR_DATE = `${FILE}${EXTRACTOR}/date`
export const FILE_EXTRACTOR_DIGIT = `${FILE}${EXTRACTOR}/digit`
export const FILE_EXTRACTOR_DIGIT_WITH_DECIMALS = `${FILE}${EXTRACTOR}/digit-with-decimals`
export const FILE_EXTRACTOR_EMAIL = `${FILE}${EXTRACTOR}/email`
export const FILE_EXTRACTOR_FILE_EXTENSION = `${FILE}${EXTRACTOR}/file-extension`
export const FILE_EXTRACTOR_HANDLE = `${FILE}${EXTRACTOR}/handle`
export const FILE_EXTRACTOR_HASHTAG = `${FILE}${EXTRACTOR}/hashtag`
export const FILE_EXTRACTOR_HEX_COLOR = `${FILE}${EXTRACTOR}/hex-color`
export const FILE_EXTRACTOR_IBAN = `${FILE}${EXTRACTOR}/iban`
export const FILE_EXTRACTOR_IP_V_4 = `${FILE}${EXTRACTOR}/ip-v-4`
export const FILE_EXTRACTOR_IP_V_6 = `${FILE}${EXTRACTOR}/ip-v-6`
export const FILE_EXTRACTOR_ISBN = `${FILE}${EXTRACTOR}/isbn`
export const FILE_EXTRACTOR_NOUN = `${FILE}${EXTRACTOR}/noun`
export const FILE_EXTRACTOR_PHONE_NUMBER = `${FILE}${EXTRACTOR}/phone-number`
export const FILE_EXTRACTOR_SENTENCE = `${FILE}${EXTRACTOR}/sentence`
export const FILE_EXTRACTOR_SINGLE_XML_TAG = `${FILE}${EXTRACTOR}/single-xml-tag`
export const FILE_EXTRACTOR_WEB_DOMAIN = `${FILE}${EXTRACTOR}/web-domain`
export const FILE_EXTRACTOR_WEB_DOMAIN_NAME = `${FILE}${EXTRACTOR}/web-domain-name`
export const FILE_EXTRACTOR_WEBSITE_URL_HASH = `${FILE}${EXTRACTOR}/website-url-hash`
export const FILE_EXTRACTOR_WEBSITE_URL_PATHNAME = `${FILE}${EXTRACTOR}/website-url-pathname`
export const FILE_EXTRACTOR_WEBSITE_URL = `${FILE}${EXTRACTOR}/website-url`
export const FILE_EXTRACTOR_XML_TAG = `${FILE}${EXTRACTOR}/xml-tag`
export const EXTRACTOR_ALPHANUMERIC = `${EXTRACTOR}/alphanumeric`
export const EXTRACTOR_BITCOIN_WALLET = `${EXTRACTOR}/bitcoin-wallet`
export const EXTRACTOR_CREDIT_CARD = `${EXTRACTOR}/credit-card`
export const EXTRACTOR_CUSTOM_REGEX = `${EXTRACTOR}/custom-regex`
export const EXTRACTOR_DATE = `${EXTRACTOR}/date`
export const EXTRACTOR_DIGIT = `${EXTRACTOR}/digit`
export const EXTRACTOR_DIGIT_WITH_DECIMALS = `${EXTRACTOR}/digit-with-decimals`
export const EXTRACTOR_EMAIL = `${EXTRACTOR}/email`
export const EXTRACTOR_FILE_EXTENSION = `${EXTRACTOR}/file-extension`
export const EXTRACTOR_HANDLE = `${EXTRACTOR}/handle`
export const EXTRACTOR_HASHTAG = `${EXTRACTOR}/hashtag`
export const EXTRACTOR_HEX_COLOR = `${EXTRACTOR}/hex-color`
export const EXTRACTOR_IBAN = `${EXTRACTOR}/iban`
export const EXTRACTOR_IP_V_4 = `${EXTRACTOR}/ip-v-4`
export const EXTRACTOR_IP_V_6 = `${EXTRACTOR}/ip-v-6`
export const EXTRACTOR_ISBN = `${EXTRACTOR}/isbn`
export const EXTRACTOR_NOUN = `${EXTRACTOR}/noun`
export const EXTRACTOR_PHONE_NUMBER = `${EXTRACTOR}/phone-number`
export const EXTRACTOR_SENTENCE = `${EXTRACTOR}/sentence`
export const EXTRACTOR_SINGLE_XML_TAG = `${EXTRACTOR}/single-xml-tag`
export const EXTRACTOR_WEB_DOMAIN = `${EXTRACTOR}/web-domain`
export const EXTRACTOR_WEB_DOMAIN_NAME = `${EXTRACTOR}/web-domain-name`
export const EXTRACTOR_WEBSITE_URL_HASH = `${EXTRACTOR}/website-url-hash`
export const EXTRACTOR_WEBSITE_URL_PATHNAME = `${EXTRACTOR}/website-url-pathname`
export const EXTRACTOR_WEBSITE_URL = `${EXTRACTOR}/website-url`
export const EXTRACTOR_XML_TAG = `${EXTRACTOR}/xml-tag`

export const ENDPOINTS = [
  FILE_TEXT,
  FILE_EXTRACTOR_ALPHANUMERIC,
  FILE_EXTRACTOR_BITCOIN_WALLET,
  FILE_EXTRACTOR_CREDIT_CARD,
  FILE_EXTRACTOR_CUSTOM_REGEX,
  FILE_EXTRACTOR_DATE,
  FILE_EXTRACTOR_DIGIT,
  FILE_EXTRACTOR_DIGIT_WITH_DECIMALS,
  FILE_EXTRACTOR_EMAIL,
  FILE_EXTRACTOR_FILE_EXTENSION,
  FILE_EXTRACTOR_HANDLE,
  FILE_EXTRACTOR_HASHTAG,
  FILE_EXTRACTOR_HEX_COLOR,
  FILE_EXTRACTOR_IBAN,
  FILE_EXTRACTOR_IP_V_4,
  FILE_EXTRACTOR_IP_V_6,
  FILE_EXTRACTOR_ISBN,
  FILE_EXTRACTOR_NOUN,
  FILE_EXTRACTOR_PHONE_NUMBER,
  FILE_EXTRACTOR_SENTENCE,
  FILE_EXTRACTOR_SINGLE_XML_TAG,
  FILE_EXTRACTOR_WEB_DOMAIN,
  FILE_EXTRACTOR_WEB_DOMAIN_NAME,
  FILE_EXTRACTOR_WEBSITE_URL_HASH,
  FILE_EXTRACTOR_WEBSITE_URL_PATHNAME,
  FILE_EXTRACTOR_WEBSITE_URL,
  FILE_EXTRACTOR_XML_TAG,
  EXTRACTOR_ALPHANUMERIC,
  EXTRACTOR_BITCOIN_WALLET,
  EXTRACTOR_CREDIT_CARD,
  EXTRACTOR_CUSTOM_REGEX,
  EXTRACTOR_DATE,
  EXTRACTOR_DIGIT,
  EXTRACTOR_DIGIT_WITH_DECIMALS,
  EXTRACTOR_EMAIL,
  EXTRACTOR_FILE_EXTENSION,
  EXTRACTOR_HANDLE,
  EXTRACTOR_HASHTAG,
  EXTRACTOR_HEX_COLOR,
  EXTRACTOR_IBAN,
  EXTRACTOR_IP_V_4,
  EXTRACTOR_IP_V_6,
  EXTRACTOR_ISBN,
  EXTRACTOR_NOUN,
  EXTRACTOR_PHONE_NUMBER,
  EXTRACTOR_SENTENCE,
  EXTRACTOR_SINGLE_XML_TAG,
  EXTRACTOR_WEB_DOMAIN,
  EXTRACTOR_WEB_DOMAIN_NAME,
  EXTRACTOR_WEBSITE_URL_HASH,
  EXTRACTOR_WEBSITE_URL_PATHNAME,
  EXTRACTOR_WEBSITE_URL,
  EXTRACTOR_XML_TAG,
]
