import { EXTRACTOR_CUSTOM_REGEX, EXTRACTOR_SINGLE_XML_TAG, FILE_EXTRACTOR_CUSTOM_REGEX, FILE_EXTRACTOR_SINGLE_XML_TAG } from '..'

export const UNIQUE_OPTIONS = ['true', 'false']

export const SORT_OPTIONS = ['az', 'za']

export const SEARCH_REQUIRED = [
  FILE_EXTRACTOR_SINGLE_XML_TAG,
  EXTRACTOR_SINGLE_XML_TAG,
  FILE_EXTRACTOR_CUSTOM_REGEX,
  EXTRACTOR_CUSTOM_REGEX
]